-- Curated seed data for the Stolen Artworks dashboard.
-- Run after database/schema.sql. The app can also load this data with npm run seed.

insert into public.stolen_artworks (
  id, title, artist, category, country_of_theft, city_of_theft, institution,
  theft_year, recovery_year, status, estimated_value_usd_m, latitude, longitude,
  image_url, source_url, source_name, notes, risk_score
) values
  ('gardner-1990-vermeer-concert', 'The Concert', 'Johannes Vermeer', 'Painting', 'United States', 'Boston', 'Isabella Stewart Gardner Museum', 1990, null, 'Missing', 200.0, 42.3386, -71.0995, 'https://www.gardnermuseum.org/sites/default/files/styles/fullscreen/public/2022-08/concert.jpg', 'https://www.gardnermuseum.org/about/theft-story', 'Isabella Stewart Gardner Museum', 'One of the works stolen during the 1990 Gardner Museum theft.', 75.4),
  ('gardner-1990-rembrandt-storm', 'Christ in the Storm on the Sea of Galilee', 'Rembrandt van Rijn', 'Painting', 'United States', 'Boston', 'Isabella Stewart Gardner Museum', 1990, null, 'Missing', 100.0, 42.3386, -71.0995, 'https://www.gardnermuseum.org/sites/default/files/styles/fullscreen/public/2022-08/storm.jpg', 'https://www.gardnermuseum.org/about/theft-story', 'Isabella Stewart Gardner Museum', 'Only known seascape by Rembrandt, stolen in the Gardner theft.', 66.4),
  ('gardner-1990-flinck-obelisk', 'Landscape with an Obelisk', 'Govaert Flinck', 'Painting', 'United States', 'Boston', 'Isabella Stewart Gardner Museum', 1990, null, 'Missing', 10.0, 42.3386, -71.0995, '', 'https://www.gardnermuseum.org/about/theft-story', 'Isabella Stewart Gardner Museum', 'Stolen in the 1990 Gardner Museum theft.', 58.3),
  ('gardner-1990-rembrandt-lady-gentleman', 'A Lady and Gentleman in Black', 'Rembrandt van Rijn', 'Painting', 'United States', 'Boston', 'Isabella Stewart Gardner Museum', 1990, null, 'Missing', 40.0, 42.3386, -71.0995, '', 'https://www.gardnermuseum.org/about/theft-story', 'Isabella Stewart Gardner Museum', 'Large Rembrandt painting stolen from the Dutch Room.', 61.0),
  ('gardner-1990-manet-tortoni', 'Chez Tortoni', 'Edouard Manet', 'Painting', 'United States', 'Boston', 'Isabella Stewart Gardner Museum', 1990, null, 'Missing', 20.0, 42.3386, -71.0995, '', 'https://www.gardnermuseum.org/about/theft-story', 'Isabella Stewart Gardner Museum', 'Manet work missing after the Gardner theft.', 59.2),
  ('gardner-1990-degas-cortege', 'Cortege aux Environs de Florence', 'Edgar Degas', 'Drawing', 'United States', 'Boston', 'Isabella Stewart Gardner Museum', 1990, null, 'Missing', 5.0, 42.3386, -71.0995, '', 'https://www.gardnermuseum.org/about/theft-story', 'Isabella Stewart Gardner Museum', 'Degas drawing stolen during the Gardner theft.', 53.9),
  ('gardner-1990-bronze-eagle', 'Napoleonic Eagle Finial', 'Unknown', 'Decorative Object', 'United States', 'Boston', 'Isabella Stewart Gardner Museum', 1990, null, 'Missing', 0.1, 42.3386, -71.0995, '', 'https://www.gardnermuseum.org/about/theft-story', 'Isabella Stewart Gardner Museum', 'Bronze finial from a Napoleonic flag staff.', 53.4),
  ('louvre-1911-mona-lisa', 'Mona Lisa', 'Leonardo da Vinci', 'Painting', 'France', 'Paris', 'Louvre Museum', 1911, 1913, 'Recovered', 860.0, 48.8606, 2.3376, 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Mona_Lisa.jpg', 'https://www.louvre.fr/en/explore/the-palace/from-theft-to-myth', 'Louvre Museum', 'Stolen from the Louvre in 1911 and recovered in Florence in 1913.', 69),
  ('oslo-1994-munch-scream', 'The Scream', 'Edvard Munch', 'Painting', 'Norway', 'Oslo', 'National Gallery of Norway', 1994, 1994, 'Recovered', 120.0, 59.9139, 10.7522, 'https://upload.wikimedia.org/wikipedia/commons/f/f4/The_Scream.jpg', 'https://www.nasjonalmuseet.no/en/collection/object/NG.M.00939', 'National Museum Norway', 'Recovered in 1994 after a high-profile theft.', 37.6),
  ('amsterdam-2002-van-gogh-scheveningen', 'View of the Sea at Scheveningen', 'Vincent van Gogh', 'Painting', 'Netherlands', 'Amsterdam', 'Van Gogh Museum', 2002, 2016, 'Recovered', 30.0, 52.3584, 4.8811, 'https://www.vangoghmuseum.nl/assets/c167b3d7-25cb-4bc8-8e82-770018ed5f8f?w=640', 'https://www.vangoghmuseum.nl/en/stories/recovered-paintings', 'Van Gogh Museum', 'Recovered in Italy in 2016 after being stolen from Amsterdam.', 26.3),
  ('amsterdam-2002-van-gogh-nuenen', 'Congregation Leaving the Reformed Church in Nuenen', 'Vincent van Gogh', 'Painting', 'Netherlands', 'Amsterdam', 'Van Gogh Museum', 2002, 2016, 'Recovered', 30.0, 52.3584, 4.8811, '', 'https://www.vangoghmuseum.nl/en/stories/recovered-paintings', 'Van Gogh Museum', 'Recovered with the Scheveningen painting in 2016.', 26.3),
  ('cairo-2010-van-gogh-poppy', 'Poppy Flowers', 'Vincent van Gogh', 'Painting', 'Egypt', 'Cairo', 'Mohamed Mahmoud Khalil Museum', 2010, null, 'Missing', 50.0, 30.0444, 31.2357, '', 'https://www.fbi.gov/wanted/topten/topten-history/hires_images/FBI-476-Hassan-Ali-Mohamed.jpg/view', 'Public reports', 'Famous Van Gogh work reported stolen from Cairo in 2010.', 53.9),
  ('palermo-1969-caravaggio-nativity', 'Nativity with St. Francis and St. Lawrence', 'Caravaggio', 'Painting', 'Italy', 'Palermo', 'Oratory of San Lorenzo', 1969, null, 'Missing', 20.0, 38.1157, 13.3615, '', 'https://www.fbi.gov/investigate/violent-crime/art-theft/top-ten-art-crimes', 'FBI Art Theft Program', 'Long-running missing masterpiece case.', 64.8),
  ('stockholm-2000-renoir-conversation', 'Conversation with a Gardener', 'Pierre-Auguste Renoir', 'Painting', 'Sweden', 'Stockholm', 'Nationalmuseum', 2000, 2005, 'Recovered', 7.5, 59.3293, 18.0686, '', 'https://www.fbi.gov/investigate/violent-crime/art-theft/top-ten-art-crimes', 'FBI Art Theft Program', 'One of several works stolen from the Nationalmuseum in 2000.', 25.1),
  ('stockholm-2000-rembrandt-selfportrait', 'Self-Portrait', 'Rembrandt van Rijn', 'Painting', 'Sweden', 'Stockholm', 'Nationalmuseum', 2000, 2005, 'Recovered', 36.0, 59.3293, 18.0686, '', 'https://www.fbi.gov/investigate/violent-crime/art-theft/top-ten-art-crimes', 'FBI Art Theft Program', 'Recovered after the armed robbery of Nationalmuseum.', 27.6),
  ('vienna-1997-saliera', 'Saliera', 'Benvenuto Cellini', 'Sculpture', 'Austria', 'Vienna', 'Kunsthistorisches Museum', 2003, 2006, 'Recovered', 60.0, 48.2038, 16.3618, '', 'https://www.khm.at/en/visit/collections/kunstkammer-wien/selected-masterpieces/benvenuto-cellini-saliera/', 'Kunsthistorisches Museum', 'Renaissance gold sculpture recovered in Austria.', 28.6),
  ('paris-2010-picasso-pigeon', 'Le pigeon aux petits pois', 'Pablo Picasso', 'Painting', 'France', 'Paris', 'Musee d''Art Moderne de Paris', 2010, null, 'Missing', 28.0, 48.8647, 2.2979, '', 'https://www.interpol.int/Crimes/Cultural-heritage-crime/Stolen-Works-of-Art-Database', 'Interpol cultural heritage crime information', 'Reported stolen from the Paris museum in 2010; recovery status remains unresolved in this teaching dataset.', 51.9),
  ('paris-2010-matisse-pastoral', 'La Pastorale', 'Henri Matisse', 'Painting', 'France', 'Paris', 'Musee d''Art Moderne de Paris', 2010, null, 'Missing', 18.0, 48.8647, 2.2979, '', 'https://www.interpol.int/Crimes/Cultural-heritage-crime/Stolen-Works-of-Art-Database', 'Interpol cultural heritage crime information', 'One of five works stolen in the Paris museum theft.', 51.0),
  ('paris-2010-modigliani-fan', 'Woman with a Fan', 'Amedeo Modigliani', 'Painting', 'France', 'Paris', 'Musee d''Art Moderne de Paris', 2010, null, 'Missing', 24.0, 48.8647, 2.2979, '', 'https://www.interpol.int/Crimes/Cultural-heritage-crime/Stolen-Works-of-Art-Database', 'Interpol cultural heritage crime information', 'High-value painting stolen in Paris in 2010.', 51.6),
  ('rotterdam-2012-picasso-harlequin', 'Harlequin Head', 'Pablo Picasso', 'Painting', 'Netherlands', 'Rotterdam', 'Kunsthal Rotterdam', 2012, null, 'Unknown', 15.0, 51.9244, 4.4777, '', 'https://www.bbc.com/news/world-europe-19967543', 'BBC public report', 'Included as unknown/unresolved status for dashboard comparison.', 33.0),
  ('rotterdam-2012-monet-waterloo', 'Waterloo Bridge, London', 'Claude Monet', 'Painting', 'Netherlands', 'Rotterdam', 'Kunsthal Rotterdam', 2012, null, 'Unknown', 20.0, 51.9244, 4.4777, '', 'https://www.bbc.com/news/world-europe-19967543', 'BBC public report', 'Stolen in the Kunsthal Rotterdam theft.', 33.4),
  ('rotterdam-2012-gauguin-woman-window', 'Woman Before a Window', 'Paul Gauguin', 'Painting', 'Netherlands', 'Rotterdam', 'Kunsthal Rotterdam', 2012, null, 'Unknown', 17.0, 51.9244, 4.4777, '', 'https://www.bbc.com/news/world-europe-19967543', 'BBC public report', 'Kunsthal Rotterdam theft case record.', 33.1),
  ('warsaw-2000-monet-beach', 'Beach in Pourville', 'Claude Monet', 'Painting', 'Poland', 'Poznan', 'National Museum in Poznan', 2000, 2010, 'Recovered', 7.0, 52.4064, 16.9252, '', 'https://www.mnp.art.pl/en/', 'National Museum in Poznan', 'Recovered after being stolen in Poland.', 25.0),
  ('miami-2019-dali-elephants', 'Les Elephants', 'Salvador Dali', 'Print', 'United States', 'San Francisco', 'Dennis Rae Fine Art', 2019, 2019, 'Recovered', 0.02, 37.7749, -122.4194, '', 'https://www.sfchronicle.com/crime/article/Dal-print-stolen-from-San-Francisco-gallery-14904385.php', 'Public news report', 'Small-value case useful for contrast against museum thefts.', 12.8),
  ('milan-1997-klimt-lady', 'Portrait of a Lady', 'Gustav Klimt', 'Painting', 'Italy', 'Piacenza', 'Ricci Oddi Gallery', 1997, 2019, 'Recovered', 66.0, 45.0526, 9.6934, '', 'https://www.bbc.com/news/world-europe-50884932', 'BBC public report', 'Found in the walls of the gallery after decades missing.', 31.5),
  ('oxford-2020-van-dyck-soldier', 'A Soldier on Horseback', 'Anthony van Dyck', 'Painting', 'United Kingdom', 'Oxford', 'Christ Church Picture Gallery', 2020, null, 'Missing', 1.3, 51.752, -1.2577, '', 'https://www.thamesvalley.police.uk/news/thames-valley/news/2020/march/16-03-2020/appeal-following-burglary-at-christ-church-picture-gallery--oxford/', 'Thames Valley Police', 'Recent unresolved case used to show time filters.', 45.5),
  ('oxford-2020-carracci-boy-drinking', 'A Boy Drinking', 'Annibale Carracci', 'Painting', 'United Kingdom', 'Oxford', 'Christ Church Picture Gallery', 2020, null, 'Missing', 1.0, 51.752, -1.2577, '', 'https://www.thamesvalley.police.uk/news/thames-valley/news/2020/march/16-03-2020/appeal-following-burglary-at-christ-church-picture-gallery--oxford/', 'Thames Valley Police', 'Stolen alongside two other paintings from Oxford.', 45.5),
  ('zurich-2008-cezanne-boy-red-waistcoat', 'Boy in a Red Waistcoat', 'Paul Cezanne', 'Painting', 'Switzerland', 'Zurich', 'Foundation E.G. Buehrle', 2008, 2012, 'Recovered', 109.0, 47.3769, 8.5417, '', 'https://www.buehrle.ch/en/collection/', 'Foundation E.G. Buehrle Collection', 'Recovered after a major Zurich art theft.', 31.0),
  ('zurich-2008-monet-poppies', 'Poppies near Vetheuil', 'Claude Monet', 'Painting', 'Switzerland', 'Zurich', 'Foundation E.G. Buehrle', 2008, 2008, 'Recovered', 44.0, 47.3769, 8.5417, '', 'https://www.buehrle.ch/en/collection/', 'Foundation E.G. Buehrle Collection', 'Recovered shortly after the theft.', 25.2),
  ('athens-2012-picasso-woman-head', 'Woman''s Head', 'Pablo Picasso', 'Painting', 'Greece', 'Athens', 'National Gallery of Greece', 2012, 2021, 'Recovered', 20.0, 37.9838, 23.7275, '', 'https://www.nationalgallery.gr/en/', 'National Gallery of Greece', 'Recovered by Greek authorities in 2021.', 21.4),
  ('athens-2012-mondrian-windmill', 'Stammer Windmill with Summer House', 'Piet Mondrian', 'Painting', 'Greece', 'Athens', 'National Gallery of Greece', 2012, 2021, 'Recovered', 8.0, 37.9838, 23.7275, '', 'https://www.nationalgallery.gr/en/', 'National Gallery of Greece', 'Recovered with the Picasso painting in 2021.', 20.3)
on conflict (id) do update set
  title = excluded.title,
  artist = excluded.artist,
  category = excluded.category,
  country_of_theft = excluded.country_of_theft,
  city_of_theft = excluded.city_of_theft,
  institution = excluded.institution,
  theft_year = excluded.theft_year,
  recovery_year = excluded.recovery_year,
  status = excluded.status,
  estimated_value_usd_m = excluded.estimated_value_usd_m,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  image_url = excluded.image_url,
  source_url = excluded.source_url,
  source_name = excluded.source_name,
  notes = excluded.notes,
  risk_score = excluded.risk_score;

insert into public.etl_runs (source_name, rows_loaded, run_status, details)
values ('curated_seed_sql', (select count(*) from public.stolen_artworks), 'success', 'Initial SQL seed completed.');
